# Variables
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# GET rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/room
Accept: application/json
Content-Type: application/json

{
    "name": "Sala de Teste via HTTP",
    "description": "Esta é uma sala de teste criada via HTTP"
}

###

@roomId = {{getRooms.response.body.$.[0].id}}

###

# GET room by ID
# @name getRoomQuestions
GET {{baseUrl}}/room/{{roomId}}/questions